### ISSUE TITLE
Official Docker image support

### ISSUE THREAD

**Issue by anthonyoteri** [anthonyoteri/dredge#6]
Create a basic `Dockerfile` to be able to run Dredge from within docker.

For example:

```sh
docker run --rm dredge registry.example.com catalog
```

**Comment by Rajdeep1311** [comment]
I would like to work sir

**Comment by anthonyoteri** [comment]
Thank you @Rajdeep1311 for wanting to help out.  If you would like to submit a pull-request that would be much appreciated.

**Comment by Rajdeep1311** [comment]
Sure sir

**Comment by Rajdeep1311** [comment]
Sir, can you tell me what tools or dependencies are to be installed to test?

**Comment by anthonyoteri** [comment]
Right now, there are no tests yet, I"m currently working on implementing a few unit tests to cover the basics.  But how I've been testing this requires an external docker registry server.  I have one locally that I've been using, but just follow the standard instructions available online to set that up, and make sure that there is at least an image pushed there.  Once that's done, running `dredge registry.local catalog` should list the images (replace registry.local) with the hostname of your registry server,  running `dredge registry.local check` should output nothing if it worked.
